set_property PACKAGE_PIN L16 [get_ports CLK]
set_property PACKAGE_PIN D18 [get_ports {LED[3]}]
set_property PACKAGE_PIN G14 [get_ports {LED[2]}]
set_property PACKAGE_PIN M15 [get_ports {LED[1]}]
set_property PACKAGE_PIN M14 [get_ports {LED[0]}]

set_property PACKAGE_PIN R18 [get_ports RST]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RST]

set_property IOSTANDARD LVCMOS33 [get_ports {red[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property PACKAGE_PIN G19 [get_ports {blue[4]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property PACKAGE_PIN K19 [get_ports {blue[2]}]
set_property PACKAGE_PIN M20 [get_ports {blue[1]}]
set_property PACKAGE_PIN P20 [get_ports {blue[0]}]
set_property PACKAGE_PIN H20 [get_ports {green[4]}]
set_property PACKAGE_PIN L19 [get_ports {green[2]}]
set_property PACKAGE_PIN N20 [get_ports {green[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {green[5]}]
set_property PACKAGE_PIN H18 [get_ports {green[0]}]
set_property PACKAGE_PIN J19 [get_ports {green[3]}]
set_property PACKAGE_PIN F20 [get_ports {green[5]}]
set_property PACKAGE_PIN F19 [get_ports {red[4]}]
set_property PACKAGE_PIN G20 [get_ports {red[3]}]
set_property PACKAGE_PIN J20 [get_ports {red[2]}]
set_property PACKAGE_PIN L20 [get_ports {red[1]}]
set_property PACKAGE_PIN M19 [get_ports {red[0]}]

set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
